multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gpfs0/jdubi/users/kasirer/Python-3.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "dots_array_new.py", line 1598, in runSingleSimulation
    currentMap=currentMap, basePath=basePath, resume=resume)
  File "dots_array_new.py", line 1221, in calcIV
    self.getToSteadyState()
  File "dots_array_new.py", line 1039, in getToSteadyState
    while steps < self.min_steps:
AttributeError: 'Simulator' object has no attribute 'min_steps'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dots_array_new.py", line 2247, in <module>
    modifyR=modifyR, constQ=constQ)
  File "dots_array_new.py", line 1719, in runFullSimulation
    result = res.get()
  File "/gpfs0/jdubi/users/kasirer/Python-3.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: 'Simulator' object has no attribute 'min_steps'
