Traceback (most recent call last):
  File "dots_array.py", line 944, in <module>
    if not os.path.exists(savePath):
  File "dots_array.py", line 720, in runFullSimulation
    avgImaps = np.mean(np.array(Imaps),axis=0)
  File "dots_array.py", line 738, in saveCurrentMaps
    blit=True)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 1174, in save
    writer.grab_frame(**savefig_kwargs)
  File "/usr/local/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 358, in finish
    self.cleanup()
  File "/usr/local/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 395, in cleanup
    out, err = self._proc.communicate()
  File "/usr/local/anaconda3/lib/python3.7/subprocess.py", line 933, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/local/anaconda3/lib/python3.7/subprocess.py", line 1666, in _communicate
    selector.register(self.stdout, selectors.EVENT_READ)
  File "/usr/local/anaconda3/lib/python3.7/selectors.py", line 352, in register
    key = super().register(fileobj, events, data)
  File "/usr/local/anaconda3/lib/python3.7/selectors.py", line 238, in register
    key = SelectorKey(fileobj, self._fileobj_lookup(fileobj), events, data)
  File "/usr/local/anaconda3/lib/python3.7/selectors.py", line 225, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/local/anaconda3/lib/python3.7/selectors.py", line 40, in _fileobj_to_fd
    "{!r}".format(fileobj)) from None
ValueError: Invalid file object: <_io.BufferedReader name=37>
